# -*- makefile -*-
# -*-Makefile-*-
#----------------------------------------------------------------------------
#       GNU ACE Workspace
#
# 
#
# This file was generated by MPC.  Any changes made directly to
# this file will be lost the next time it is generated.
#
# MPC Command:
# /home/martina-galli/OpenDDS/ACE_wrappers/bin/mwc.pl -type gnuace
#
#----------------------------------------------------------------------------

MAKEFILE = GNUmakefile

ifeq ($(findstring k,$(MAKEFLAGS)),k)
  KEEP_GOING = -
endif

include $(ACE_ROOT)/include/makeinclude/macros.GNU

all: Sitrep_Publisher

depend: Sitrep_Publisher-depend

REMAINING_TARGETS := $(filter-out all depend,$(TARGETS_NESTED:.nested=)) $(CUSTOM_TARGETS)
.PHONY: $(REMAINING_TARGETS)

$(REMAINING_TARGETS):
	$(KEEP_GOING)@$(MAKE) -f GNUmakefile.Sitrep_Publisher $(@)

.PHONY: Sitrep_Publisher
Sitrep_Publisher:
	$(KEEP_GOING)@$(MAKE) -f GNUmakefile.Sitrep_Publisher all

.PHONY: Sitrep_Publisher-depend
Sitrep_Publisher-depend:
	$(KEEP_GOING)@$(MAKE) -f GNUmakefile.Sitrep_Publisher depend

project_name_list:
	@echo Sitrep_Publisher
