// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.5.23
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       https://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     https://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// /home/martina-galli/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_codegen.cpp:372


#include "SitrepTypeSupportC.h"
#include "tao/CDR.h"
#include "ace/OS_NS_string.h"

#if !defined (__ACE_INLINE__)
#include "SitrepTypeSupportC.inl"
#endif /* !defined INLINE */
// TAO_IDL - Generated from
// /home/martina-galli/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_interface/interface_cs.cpp:47


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations for DefenseData::SitrepMessageTypeSupport.

DefenseData::SitrepMessageTypeSupport_ptr
TAO::Objref_Traits<DefenseData::SitrepMessageTypeSupport>::duplicate (
    DefenseData::SitrepMessageTypeSupport_ptr p)
{
  return DefenseData::SitrepMessageTypeSupport::_duplicate (p);
}

void
TAO::Objref_Traits<DefenseData::SitrepMessageTypeSupport>::release (
    DefenseData::SitrepMessageTypeSupport_ptr p)
{
  ::CORBA::release (p);
}

DefenseData::SitrepMessageTypeSupport_ptr
TAO::Objref_Traits<DefenseData::SitrepMessageTypeSupport>::nil (void)
{
  return DefenseData::SitrepMessageTypeSupport::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<DefenseData::SitrepMessageTypeSupport>::marshal (
    const DefenseData::SitrepMessageTypeSupport_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

TAO_END_VERSIONED_NAMESPACE_DECL



DefenseData::SitrepMessageTypeSupport::SitrepMessageTypeSupport (void)
{}

DefenseData::SitrepMessageTypeSupport::~SitrepMessageTypeSupport (void)
{
}

DefenseData::SitrepMessageTypeSupport_ptr
DefenseData::SitrepMessageTypeSupport::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return SitrepMessageTypeSupport::_duplicate (
      dynamic_cast<SitrepMessageTypeSupport_ptr> (_tao_objref));
}

DefenseData::SitrepMessageTypeSupport_ptr
DefenseData::SitrepMessageTypeSupport::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return SitrepMessageTypeSupport::_duplicate (
      dynamic_cast<SitrepMessageTypeSupport_ptr> (_tao_objref));
}

DefenseData::SitrepMessageTypeSupport_ptr
DefenseData::SitrepMessageTypeSupport::_nil (void)
{
  return 0;
}

DefenseData::SitrepMessageTypeSupport_ptr
DefenseData::SitrepMessageTypeSupport::_duplicate (SitrepMessageTypeSupport_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
DefenseData::SitrepMessageTypeSupport::_tao_release (SitrepMessageTypeSupport_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
DefenseData::SitrepMessageTypeSupport::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/TypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:OpenDDS/DCPS/TypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:DefenseData/SitrepMessageTypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* DefenseData::SitrepMessageTypeSupport::_interface_repository_id (void) const
{
  return "IDL:DefenseData/SitrepMessageTypeSupport:1.0";
}

::CORBA::Boolean
DefenseData::SitrepMessageTypeSupport::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}
// TAO_IDL - Generated from
// /home/martina-galli/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_interface/interface_cs.cpp:47


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations for DefenseData::SitrepMessageDataWriter.

DefenseData::SitrepMessageDataWriter_ptr
TAO::Objref_Traits<DefenseData::SitrepMessageDataWriter>::duplicate (
    DefenseData::SitrepMessageDataWriter_ptr p)
{
  return DefenseData::SitrepMessageDataWriter::_duplicate (p);
}

void
TAO::Objref_Traits<DefenseData::SitrepMessageDataWriter>::release (
    DefenseData::SitrepMessageDataWriter_ptr p)
{
  ::CORBA::release (p);
}

DefenseData::SitrepMessageDataWriter_ptr
TAO::Objref_Traits<DefenseData::SitrepMessageDataWriter>::nil (void)
{
  return DefenseData::SitrepMessageDataWriter::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<DefenseData::SitrepMessageDataWriter>::marshal (
    const DefenseData::SitrepMessageDataWriter_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

TAO_END_VERSIONED_NAMESPACE_DECL



DefenseData::SitrepMessageDataWriter::SitrepMessageDataWriter (void)
{}

DefenseData::SitrepMessageDataWriter::~SitrepMessageDataWriter (void)
{
}

DefenseData::SitrepMessageDataWriter_ptr
DefenseData::SitrepMessageDataWriter::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return SitrepMessageDataWriter::_duplicate (
      dynamic_cast<SitrepMessageDataWriter_ptr> (_tao_objref));
}

DefenseData::SitrepMessageDataWriter_ptr
DefenseData::SitrepMessageDataWriter::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return SitrepMessageDataWriter::_duplicate (
      dynamic_cast<SitrepMessageDataWriter_ptr> (_tao_objref));
}

DefenseData::SitrepMessageDataWriter_ptr
DefenseData::SitrepMessageDataWriter::_nil (void)
{
  return 0;
}

DefenseData::SitrepMessageDataWriter_ptr
DefenseData::SitrepMessageDataWriter::_duplicate (SitrepMessageDataWriter_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
DefenseData::SitrepMessageDataWriter::_tao_release (SitrepMessageDataWriter_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
DefenseData::SitrepMessageDataWriter::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/Entity:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:DDS/DataWriter:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:DefenseData/SitrepMessageDataWriter:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* DefenseData::SitrepMessageDataWriter::_interface_repository_id (void) const
{
  return "IDL:DefenseData/SitrepMessageDataWriter:1.0";
}

::CORBA::Boolean
DefenseData::SitrepMessageDataWriter::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}
// TAO_IDL - Generated from
// /home/martina-galli/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_interface/interface_cs.cpp:47


TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations for DefenseData::SitrepMessageDataReader.

DefenseData::SitrepMessageDataReader_ptr
TAO::Objref_Traits<DefenseData::SitrepMessageDataReader>::duplicate (
    DefenseData::SitrepMessageDataReader_ptr p)
{
  return DefenseData::SitrepMessageDataReader::_duplicate (p);
}

void
TAO::Objref_Traits<DefenseData::SitrepMessageDataReader>::release (
    DefenseData::SitrepMessageDataReader_ptr p)
{
  ::CORBA::release (p);
}

DefenseData::SitrepMessageDataReader_ptr
TAO::Objref_Traits<DefenseData::SitrepMessageDataReader>::nil (void)
{
  return DefenseData::SitrepMessageDataReader::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<DefenseData::SitrepMessageDataReader>::marshal (
    const DefenseData::SitrepMessageDataReader_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

TAO_END_VERSIONED_NAMESPACE_DECL



DefenseData::SitrepMessageDataReader::SitrepMessageDataReader (void)
{}

DefenseData::SitrepMessageDataReader::~SitrepMessageDataReader (void)
{
}

DefenseData::SitrepMessageDataReader_ptr
DefenseData::SitrepMessageDataReader::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return SitrepMessageDataReader::_duplicate (
      dynamic_cast<SitrepMessageDataReader_ptr> (_tao_objref));
}

DefenseData::SitrepMessageDataReader_ptr
DefenseData::SitrepMessageDataReader::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return SitrepMessageDataReader::_duplicate (
      dynamic_cast<SitrepMessageDataReader_ptr> (_tao_objref));
}

DefenseData::SitrepMessageDataReader_ptr
DefenseData::SitrepMessageDataReader::_nil (void)
{
  return 0;
}

DefenseData::SitrepMessageDataReader_ptr
DefenseData::SitrepMessageDataReader::_duplicate (SitrepMessageDataReader_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
DefenseData::SitrepMessageDataReader::_tao_release (SitrepMessageDataReader_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
DefenseData::SitrepMessageDataReader::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/Entity:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:DDS/DataReader:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:OpenDDS/DCPS/DataReaderEx:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:DefenseData/SitrepMessageDataReader:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* DefenseData::SitrepMessageDataReader::_interface_repository_id (void) const
{
  return "IDL:DefenseData/SitrepMessageDataReader:1.0";
}

::CORBA::Boolean
DefenseData::SitrepMessageDataReader::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}

