/* -*- C++ -*- */
/* Generated by /home/martina-galli/OpenDDS/bin/opendds_idl version 3.34.0-dev (ACE version 6.5.23) running on input file Sitrep.idl */
#ifndef OPENDDS_IDL_GENERATED_SITREPTYPESUPPORTIMPL_H_X6USN2
#define OPENDDS_IDL_GENERATED_SITREPTYPESUPPORTIMPL_H_X6USN2

#include <dds/Version.h>
#if !OPENDDS_VERSION_EXACTLY(3, 34, 0)
#  error "This file should be regenerated with opendds_idl"
#endif
#include <dds/DCPS/Definitions.h>

#include <dds/DdsDcpsC.h>

#include "SitrepC.h"
#include "SitrepTypeSupportC.h"
#include "dds/DCPS/Serializer.h"
#include "dds/DCPS/Service_Participant.h"
#include "dds/DCPS/TypeSupportImpl.h"
#include "dds/DCPS/TypeSupportImpl_T.h"
#include "dds/DCPS/Util.h"
#include "dds/DCPS/ValueDispatcher.h"
#include "dds/DCPS/ValueReader.h"
#include "dds/DCPS/ValueWriter.h"
#include "dds/DCPS/XTypes/DynamicDataAdapter.h"
#include "dds/DCPS/XTypes/TypeObject.h"


/* Begin MODULE: CORBA */


/* End MODULE: CORBA */


/* Begin MODULE: DefenseData */



/* Begin STRUCT: SitrepMessage */

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

struct DefenseData_SitrepMessage_xtag {};
template<> const XTypes::TypeIdentifier& getMinimalTypeIdentifier<DefenseData_SitrepMessage_xtag>();

template<> const XTypes::TypeMap& getMinimalTypeMap<DefenseData_SitrepMessage_xtag>();

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

bool vread(OpenDDS::DCPS::ValueReader& value_reader,  ::DefenseData::SitrepMessage& value);

bool vread(OpenDDS::DCPS::ValueReader& value_reader, const NestedKeyOnly< ::DefenseData::SitrepMessage>& value);

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

bool vwrite(OpenDDS::DCPS::ValueWriter& value_writer, const  ::DefenseData::SitrepMessage& value);

bool vwrite(OpenDDS::DCPS::ValueWriter& value_writer, const NestedKeyOnly<const  ::DefenseData::SitrepMessage>& value);

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

template<> void set_default( ::DefenseData::SitrepMessage& stru);

void serialized_size(const Encoding& encoding, size_t& size, const ::DefenseData::SitrepMessage& stru);

bool operator<<(Serializer& strm, const ::DefenseData::SitrepMessage& stru);

bool operator>>(Serializer& strm,  ::DefenseData::SitrepMessage& stru);

void serialized_size(const Encoding& encoding, size_t& size, const NestedKeyOnly<const ::DefenseData::SitrepMessage>& stru);

bool operator<<(Serializer& strm, const NestedKeyOnly<const ::DefenseData::SitrepMessage>& stru);

bool operator>>(Serializer& strm, const NestedKeyOnly< ::DefenseData::SitrepMessage>& stru);

template <>
struct MarshalTraits< ::DefenseData::SitrepMessage> {
  static void representations_allowed_by_type(DDS::DataRepresentationIdSeq& seq)
  {
    seq.length(4);
    seq[0] = DDS::XCDR_DATA_REPRESENTATION;
    seq[1] = DDS::XCDR2_DATA_REPRESENTATION;
    seq[2] = DDS::XML_DATA_REPRESENTATION;
    seq[3] = OpenDDS::DCPS::UNALIGNED_CDR_DATA_REPRESENTATION;
  }

  static SerializedSizeBound serialized_size_bound(const Encoding& encoding)
  {
    switch (encoding.kind()) {
    case Encoding::KIND_XCDR1:
      return SerializedSizeBound();
    case Encoding::KIND_XCDR2:
      return SerializedSizeBound();
    case Encoding::KIND_UNALIGNED_CDR:
      return SerializedSizeBound();
    default:
      OPENDDS_ASSERT(false);
      return SerializedSizeBound();
    }
  }

  static SerializedSizeBound key_only_serialized_size_bound(const Encoding& encoding)
  {
    switch (encoding.kind()) {
    case Encoding::KIND_XCDR1:
      return SerializedSizeBound();
    case Encoding::KIND_XCDR2:
      return SerializedSizeBound();
    case Encoding::KIND_UNALIGNED_CDR:
      return SerializedSizeBound(4);
    default:
      OPENDDS_ASSERT(false);
      return SerializedSizeBound();
    }
  }

  static bool to_message_block(ACE_Message_Block&, const  ::DefenseData::SitrepMessage&) { return false; }
  static bool from_message_block( ::DefenseData::SitrepMessage&, const ACE_Message_Block&) { return false; }
  static Extensibility extensibility() { return APPENDABLE; }
  static Extensibility max_extensibility_level() { return APPENDABLE; }
};
void serialized_size(const Encoding& encoding, size_t& size, const KeyOnly<const  ::DefenseData::SitrepMessage> stru);

bool operator<<(Serializer& strm, KeyOnly<const  ::DefenseData::SitrepMessage> stru);

bool operator>>(Serializer& strm, KeyOnly< ::DefenseData::SitrepMessage> stru);

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL


namespace DefenseData {
/// This structure supports use of std::map with one or more keys.
struct  SitrepMessage_OpenDDS_KeyLessThan {
  bool operator()(const  ::DefenseData::SitrepMessage& v1, const  ::DefenseData::SitrepMessage& v2) const
  {
    using ::operator<; // TAO::String_Manager's operator< is in global NS
    if (v1.trackId < v2.trackId) return true;
    if (v2.trackId < v1.trackId) return false;
    return false;
  }
};
}

namespace DefenseData {
class SitrepMessageTypeSupportImpl;
}
OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS {
namespace DCPS {
template <>
struct DDSTraits< ::DefenseData::SitrepMessage> {
  typedef  ::DefenseData::SitrepMessage MessageType;
  typedef  ::DefenseData::SitrepMessageSeq MessageSequenceType;
  typedef  ::DefenseData::SitrepMessageSeq::PrivateMemberAccess MessageSequenceAdapterType;
  typedef  ::DefenseData::SitrepMessageTypeSupport TypeSupportType;
  typedef  ::DefenseData::SitrepMessageTypeSupportImpl TypeSupportImplType;
  typedef  ::DefenseData::SitrepMessageDataWriter DataWriterType;
  typedef  ::DefenseData::SitrepMessageDataReader DataReaderType;
  typedef  ::DefenseData::SitrepMessage_OpenDDS_KeyLessThan LessThanType;
  typedef OpenDDS::DCPS::KeyOnly<const  ::DefenseData::SitrepMessage> KeyOnlyType;
  typedef OpenDDS::DCPS::DefenseData_SitrepMessage_xtag XtagType;

  static const char* type_name() { return "DefenseData::SitrepMessage"; }
  static size_t key_count() { return 1; }
  static bool is_key(const char*);
};
} // namespace DCPS
} // namespace OpenDDS
OPENDDS_END_VERSIONED_NAMESPACE_DECL

namespace DefenseData {
class  SitrepMessageTypeSupportImpl
  : public virtual OpenDDS::DCPS::TypeSupportImpl_T<SitrepMessage>
  , public virtual OpenDDS::DCPS::ValueDispatcher_T<SitrepMessage>
{
public:
  typedef SitrepMessageTypeSupport TypeSupportType;
  typedef SitrepMessageTypeSupport::_var_type _var_type;
  typedef SitrepMessageTypeSupport::_ptr_type _ptr_type;

  SitrepMessageTypeSupportImpl() {}
  virtual ~SitrepMessageTypeSupportImpl() {}

  virtual ::DDS::DataWriter_ptr create_datawriter();
  virtual ::DDS::DataReader_ptr create_datareader();
#ifndef OPENDDS_NO_MULTI_TOPIC
  virtual ::DDS::DataReader_ptr create_multitopic_datareader();
#endif /* !OPENDDS_NO_MULTI_TOPIC */
#ifndef OPENDDS_SAFETY_PROFILE
  SitrepMessage* create_sample(::DDS::DynamicData_ptr src);
#endif
#ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE
  virtual const OpenDDS::DCPS::MetaStruct& getMetaStructForType() const;
#endif /* !OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE */

  virtual const OpenDDS::XTypes::TypeIdentifier& getMinimalTypeIdentifier() const;
  virtual const OpenDDS::XTypes::TypeMap& getMinimalTypeMap() const;

  virtual const OpenDDS::XTypes::TypeIdentifier& getCompleteTypeIdentifier() const;
  virtual const OpenDDS::XTypes::TypeMap& getCompleteTypeMap() const;

  ::DDS::ReturnCode_t encode_to_string(const SitrepMessage& in, CORBA::String_out out, OpenDDS::DCPS::RepresentationFormat* format);
  ::DDS::ReturnCode_t encode_to_bytes(const SitrepMessage& in, ::DDS::OctetSeq_out out, OpenDDS::DCPS::RepresentationFormat* format);
  ::DDS::ReturnCode_t decode_from_string(const char* in, SitrepMessage_out out, OpenDDS::DCPS::RepresentationFormat* format);
  ::DDS::ReturnCode_t decode_from_bytes(const ::DDS::OctetSeq& in, SitrepMessage_out out, OpenDDS::DCPS::RepresentationFormat* format);

  static SitrepMessageTypeSupport::_ptr_type _narrow(CORBA::Object_ptr obj);
};

}
#ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE
OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

class MetaStruct;

template<typename T>
const MetaStruct& getMetaStruct();

template<>
const MetaStruct& getMetaStruct< ::DefenseData::SitrepMessage>();
bool gen_skip_over(Serializer& ser,  ::DefenseData::SitrepMessage*);

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

#endif // ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE

OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace XTypes {

#ifndef OPENDDS_SAFETY_PROFILE
template <>
DDS::DynamicData_ptr get_dynamic_data_adapter< ::DefenseData::SitrepMessage,  ::DefenseData::SitrepMessage>(DDS::DynamicType_ptr type, const  ::DefenseData::SitrepMessage& value);

template <>
DDS::DynamicData_ptr get_dynamic_data_adapter< ::DefenseData::SitrepMessage,  ::DefenseData::SitrepMessage>(DDS::DynamicType_ptr type,  ::DefenseData::SitrepMessage& value);

template <>
const  ::DefenseData::SitrepMessage* get_dynamic_data_adapter_value< ::DefenseData::SitrepMessage,  ::DefenseData::SitrepMessage>(DDS::DynamicData_ptr dd);

#endif // ifndef OPENDDS_SAFETY_PROFILE

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL


/* End STRUCT: SitrepMessage */

/* End MODULE: DefenseData */
OPENDDS_BEGIN_VERSIONED_NAMESPACE_DECL
namespace OpenDDS { namespace DCPS {

} }
OPENDDS_END_VERSIONED_NAMESPACE_DECL

#endif /* OPENDDS_IDL_GENERATED_SITREPTYPESUPPORTIMPL_H_X6USN2 */
