// -*- C++ -*-
/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.5.23
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       https://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     https://www.dre.vanderbilt.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// /home/martina-galli/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_codegen.cpp:148

#ifndef _TAO_IDL_SITREPTYPESUPPORTC_0PH0P8_H_
#define _TAO_IDL_SITREPTYPESUPPORTC_0PH0P8_H_

#include /**/ "ace/pre.h"


#include /**/ "ace/config-all.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */


#include "tao/ORB.h"
#include "tao/SystemException.h"
#include "tao/Basic_Types_IDLv4.h"
TAO_BEGIN_VERSIONED_NAMESPACE_DECL

namespace CORBA
{
  using namespace IDLv4;
}

TAO_END_VERSIONED_NAMESPACE_DECL

#include "tao/ORB_Constants.h"
#include "dds/DCPS/ZeroCopyInfoSeq_T.h"
#include "dds/DCPS/ZeroCopySeq_T.h"
#include "tao/Object.h"
#include "tao/String_Manager_T.h"
#include "tao/Sequence_T.h"
#include "tao/Objref_VarOut_T.h"
#include "tao/Seq_Var_T.h"
#include "tao/Seq_Out_T.h"
#include "tao/Arg_Traits_T.h"
#include "tao/Basic_Arguments.h"
#include "tao/Special_Basic_Arguments.h"
#include "tao/Any_Insert_Policy_T.h"
#include "tao/Fixed_Size_Argument_T.h"
#include "tao/Var_Size_Argument_T.h"
#include "tao/Object_Argument_T.h"
#include "tao/UB_String_Arguments.h"
#include /**/ "tao/Version.h"
#include /**/ "tao/Versioned_Namespace.h"

#include "SitrepC.h"
#include "dds/DdsDcpsInfrastructureC.h"
#include "dds/DdsDcpsPublicationC.h"
#include "dds/DdsDcpsSubscriptionExtC.h"
#include "dds/DdsDcpsTopicC.h"
#include "dds/DdsDcpsTypeSupportExtC.h"
#include "dds/DdsDynamicDataC.h"

#if TAO_MAJOR_VERSION != 2 || TAO_MINOR_VERSION != 5 || TAO_MICRO_VERSION != 23
#error This file should be regenerated with TAO_IDL
#endif
// TAO_IDL - Generated from
// /home/martina-galli/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_module/module_ch.cpp:34

namespace DefenseData
{

  
  // TAO_IDL - Generated from
  // /home/martina-galli/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_sequence/sequence_ch.cpp:98

  

  typedef ::TAO::DCPS::ZeroCopyDataSeq< DefenseData::SitrepMessage, DCPS_ZERO_COPY_SEQ_DEFAULT_SIZE> SitrepMessageSeq;
  
  // TAO_IDL - Generated from
  // /home/martina-galli/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_interface.cpp:747

  

#if !defined (_DEFENSEDATA_SITREPMESSAGETYPESUPPORT__VAR_OUT_CH_)
#define _DEFENSEDATA_SITREPMESSAGETYPESUPPORT__VAR_OUT_CH_

  class SitrepMessageTypeSupport;
  typedef SitrepMessageTypeSupport *SitrepMessageTypeSupport_ptr;
  typedef TAO_Objref_Var_T<SitrepMessageTypeSupport> SitrepMessageTypeSupport_var;
  typedef TAO_Objref_Out_T<SitrepMessageTypeSupport> SitrepMessageTypeSupport_out;
  

#endif /* end #if !defined */

  
  // TAO_IDL - Generated from
  // /home/martina-galli/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_interface/interface_ch.cpp:39

  

  class  SitrepMessageTypeSupport
    : public virtual ::OpenDDS::DCPS::TypeSupport
  
  {
  public:
    // TAO_IDL - Generated from
    // /home/martina-galli/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:302

    typedef SitrepMessageTypeSupport_ptr _ptr_type;
    typedef SitrepMessageTypeSupport_var _var_type;
    typedef SitrepMessageTypeSupport_out _out_type;

    // The static operations.
    static SitrepMessageTypeSupport_ptr _duplicate (SitrepMessageTypeSupport_ptr obj);

    static void _tao_release (SitrepMessageTypeSupport_ptr obj);

    static SitrepMessageTypeSupport_ptr _narrow (::CORBA::Object_ptr obj);
    static SitrepMessageTypeSupport_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static SitrepMessageTypeSupport_ptr _nil (void);

    virtual ::DDS::ReturnCode_t create_sample_rc (
      ::DefenseData::SitrepMessage & dst,
      ::DDS::DynamicData_ptr src) = 0;

    virtual ::DefenseData::SitrepMessage * create_sample (
      ::DDS::DynamicData_ptr src) = 0;

    virtual ::DDS::ReturnCode_t create_dynamic_sample_rc (
      ::DDS::DynamicData_ptr & dst,
      const ::DefenseData::SitrepMessage & src) = 0;

    virtual ::DDS::DynamicData_ptr create_dynamic_sample (
      const ::DefenseData::SitrepMessage & src) = 0;

    virtual ::DDS::ReturnCode_t encode_to_string (
      const ::DefenseData::SitrepMessage & sample,
      ::CORBA::String_out encoded,
      ::OpenDDS::DCPS::RepresentationFormat_ptr format) = 0;

    virtual ::DDS::ReturnCode_t encode_to_bytes (
      const ::DefenseData::SitrepMessage & sample,
      ::DDS::OctetSeq_out encoded,
      ::OpenDDS::DCPS::RepresentationFormat_ptr format) = 0;

    virtual ::DDS::ReturnCode_t decode_from_string (
      const char * encoded,
      ::DefenseData::SitrepMessage_out sample,
      ::OpenDDS::DCPS::RepresentationFormat_ptr format) = 0;

    virtual ::DDS::ReturnCode_t decode_from_bytes (
      const ::DDS::OctetSeq & encoded,
      ::DefenseData::SitrepMessage_out sample,
      ::OpenDDS::DCPS::RepresentationFormat_ptr format) = 0;

    
    // TAO_IDL - Generated from
    // /home/martina-galli/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_interface/interface_ch.cpp:135

    

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    SitrepMessageTypeSupport (void);

    

    virtual ~SitrepMessageTypeSupport (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    ACE_UNIMPLEMENTED_FUNC (SitrepMessageTypeSupport (const SitrepMessageTypeSupport &))
#if defined (ACE_HAS_CPP11)
    ACE_UNIMPLEMENTED_FUNC (SitrepMessageTypeSupport (SitrepMessageTypeSupport &&))
#endif /* ACE_HAS_CPP11 */
    ACE_UNIMPLEMENTED_FUNC (SitrepMessageTypeSupport &operator= (const SitrepMessageTypeSupport &))
#if defined (ACE_HAS_CPP11)
    ACE_UNIMPLEMENTED_FUNC (SitrepMessageTypeSupport &operator= (SitrepMessageTypeSupport &&))
#endif /* ACE_HAS_CPP11 */
  };
  // TAO_IDL - Generated from
  // /home/martina-galli/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_interface.cpp:747

  

#if !defined (_DEFENSEDATA_SITREPMESSAGEDATAWRITER__VAR_OUT_CH_)
#define _DEFENSEDATA_SITREPMESSAGEDATAWRITER__VAR_OUT_CH_

  class SitrepMessageDataWriter;
  typedef SitrepMessageDataWriter *SitrepMessageDataWriter_ptr;
  typedef TAO_Objref_Var_T<SitrepMessageDataWriter> SitrepMessageDataWriter_var;
  typedef TAO_Objref_Out_T<SitrepMessageDataWriter> SitrepMessageDataWriter_out;
  

#endif /* end #if !defined */

  
  // TAO_IDL - Generated from
  // /home/martina-galli/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_interface/interface_ch.cpp:39

  

  class  SitrepMessageDataWriter
    : public virtual ::DDS::DataWriter
  
  {
  public:
    // TAO_IDL - Generated from
    // /home/martina-galli/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:302

    typedef SitrepMessageDataWriter_ptr _ptr_type;
    typedef SitrepMessageDataWriter_var _var_type;
    typedef SitrepMessageDataWriter_out _out_type;

    // The static operations.
    static SitrepMessageDataWriter_ptr _duplicate (SitrepMessageDataWriter_ptr obj);

    static void _tao_release (SitrepMessageDataWriter_ptr obj);

    static SitrepMessageDataWriter_ptr _narrow (::CORBA::Object_ptr obj);
    static SitrepMessageDataWriter_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static SitrepMessageDataWriter_ptr _nil (void);

    virtual ::DDS::InstanceHandle_t register_instance (
      const ::DefenseData::SitrepMessage & instance) = 0;

    virtual ::DDS::InstanceHandle_t register_instance_w_timestamp (
      const ::DefenseData::SitrepMessage & instance,
      const ::DDS::Time_t & timestamp) = 0;

    virtual ::DDS::ReturnCode_t unregister_instance (
      const ::DefenseData::SitrepMessage & instance,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::ReturnCode_t unregister_instance_w_timestamp (
      const ::DefenseData::SitrepMessage & instance,
      ::DDS::InstanceHandle_t handle,
      const ::DDS::Time_t & timestamp) = 0;

    virtual ::DDS::ReturnCode_t write (
      const ::DefenseData::SitrepMessage & instance_data,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::ReturnCode_t write_w_timestamp (
      const ::DefenseData::SitrepMessage & instance_data,
      ::DDS::InstanceHandle_t handle,
      const ::DDS::Time_t & source_timestamp) = 0;

    virtual ::DDS::ReturnCode_t dispose (
      const ::DefenseData::SitrepMessage & instance_data,
      ::DDS::InstanceHandle_t instance_handle) = 0;

    virtual ::DDS::ReturnCode_t dispose_w_timestamp (
      const ::DefenseData::SitrepMessage & instance_data,
      ::DDS::InstanceHandle_t instance_handle,
      const ::DDS::Time_t & source_timestamp) = 0;

    virtual ::DDS::ReturnCode_t get_key_value (
      ::DefenseData::SitrepMessage & key_holder,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::InstanceHandle_t lookup_instance (
      const ::DefenseData::SitrepMessage & instance_data) = 0;

    
    // TAO_IDL - Generated from
    // /home/martina-galli/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_interface/interface_ch.cpp:135

    

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    SitrepMessageDataWriter (void);

    

    virtual ~SitrepMessageDataWriter (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    ACE_UNIMPLEMENTED_FUNC (SitrepMessageDataWriter (const SitrepMessageDataWriter &))
#if defined (ACE_HAS_CPP11)
    ACE_UNIMPLEMENTED_FUNC (SitrepMessageDataWriter (SitrepMessageDataWriter &&))
#endif /* ACE_HAS_CPP11 */
    ACE_UNIMPLEMENTED_FUNC (SitrepMessageDataWriter &operator= (const SitrepMessageDataWriter &))
#if defined (ACE_HAS_CPP11)
    ACE_UNIMPLEMENTED_FUNC (SitrepMessageDataWriter &operator= (SitrepMessageDataWriter &&))
#endif /* ACE_HAS_CPP11 */
  };
  // TAO_IDL - Generated from
  // /home/martina-galli/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_interface.cpp:747

  

#if !defined (_DEFENSEDATA_SITREPMESSAGEDATAREADER__VAR_OUT_CH_)
#define _DEFENSEDATA_SITREPMESSAGEDATAREADER__VAR_OUT_CH_

  class SitrepMessageDataReader;
  typedef SitrepMessageDataReader *SitrepMessageDataReader_ptr;
  typedef TAO_Objref_Var_T<SitrepMessageDataReader> SitrepMessageDataReader_var;
  typedef TAO_Objref_Out_T<SitrepMessageDataReader> SitrepMessageDataReader_out;
  

#endif /* end #if !defined */

  
  // TAO_IDL - Generated from
  // /home/martina-galli/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_interface/interface_ch.cpp:39

  

  class  SitrepMessageDataReader
    : public virtual ::OpenDDS::DCPS::DataReaderEx
  
  {
  public:
    // TAO_IDL - Generated from
    // /home/martina-galli/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_type.cpp:302

    typedef SitrepMessageDataReader_ptr _ptr_type;
    typedef SitrepMessageDataReader_var _var_type;
    typedef SitrepMessageDataReader_out _out_type;

    // The static operations.
    static SitrepMessageDataReader_ptr _duplicate (SitrepMessageDataReader_ptr obj);

    static void _tao_release (SitrepMessageDataReader_ptr obj);

    static SitrepMessageDataReader_ptr _narrow (::CORBA::Object_ptr obj);
    static SitrepMessageDataReader_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static SitrepMessageDataReader_ptr _nil (void);

    virtual ::DDS::ReturnCode_t read (
      ::DefenseData::SitrepMessageSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t take (
      ::DefenseData::SitrepMessageSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t read_w_condition (
      ::DefenseData::SitrepMessageSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t take_w_condition (
      ::DefenseData::SitrepMessageSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t read_next_sample (
      ::DefenseData::SitrepMessage & received_data,
      ::DDS::SampleInfo & sample_info) = 0;

    virtual ::DDS::ReturnCode_t take_next_sample (
      ::DefenseData::SitrepMessage & received_data,
      ::DDS::SampleInfo & sample_info) = 0;

    virtual ::DDS::ReturnCode_t read_instance (
      ::DefenseData::SitrepMessageSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t take_instance (
      ::DefenseData::SitrepMessageSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t read_instance_w_condition (
      ::DefenseData::SitrepMessageSeq & received_data,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t take_instance_w_condition (
      ::DefenseData::SitrepMessageSeq & received_data,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t read_next_instance (
      ::DefenseData::SitrepMessageSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t take_next_instance (
      ::DefenseData::SitrepMessageSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t read_next_instance_w_condition (
      ::DefenseData::SitrepMessageSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t previous_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t take_next_instance_w_condition (
      ::DefenseData::SitrepMessageSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t previous_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t return_loan (
      ::DefenseData::SitrepMessageSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq) = 0;

    virtual ::DDS::ReturnCode_t get_key_value (
      ::DefenseData::SitrepMessage & key_holder,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::InstanceHandle_t lookup_instance (
      const ::DefenseData::SitrepMessage & instance_data) = 0;

    
    // TAO_IDL - Generated from
    // /home/martina-galli/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_interface/interface_ch.cpp:135

    

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    SitrepMessageDataReader (void);

    

    virtual ~SitrepMessageDataReader (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    ACE_UNIMPLEMENTED_FUNC (SitrepMessageDataReader (const SitrepMessageDataReader &))
#if defined (ACE_HAS_CPP11)
    ACE_UNIMPLEMENTED_FUNC (SitrepMessageDataReader (SitrepMessageDataReader &&))
#endif /* ACE_HAS_CPP11 */
    ACE_UNIMPLEMENTED_FUNC (SitrepMessageDataReader &operator= (const SitrepMessageDataReader &))
#if defined (ACE_HAS_CPP11)
    ACE_UNIMPLEMENTED_FUNC (SitrepMessageDataReader &operator= (SitrepMessageDataReader &&))
#endif /* ACE_HAS_CPP11 */
  };


// TAO_IDL - Generated from
// /home/martina-galli/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_module/module_ch.cpp:62


} // module DefenseData
// TAO_IDL - Generated from
// /home/martina-galli/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_arg_traits.cpp:64



TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{
}

TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// /home/martina-galli/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_visitor_traits.cpp:58



TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations.
namespace TAO
{

#if !defined (_DEFENSEDATA_SITREPMESSAGETYPESUPPORT__TRAITS_)
#define _DEFENSEDATA_SITREPMESSAGETYPESUPPORT__TRAITS_

  template<>
  struct  Objref_Traits< ::DefenseData::SitrepMessageTypeSupport>
  {
    static ::DefenseData::SitrepMessageTypeSupport_ptr duplicate (
        ::DefenseData::SitrepMessageTypeSupport_ptr p);
    static void release (
        ::DefenseData::SitrepMessageTypeSupport_ptr p);
    static ::DefenseData::SitrepMessageTypeSupport_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::DefenseData::SitrepMessageTypeSupport_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */

#if !defined (_DEFENSEDATA_SITREPMESSAGEDATAWRITER__TRAITS_)
#define _DEFENSEDATA_SITREPMESSAGEDATAWRITER__TRAITS_

  template<>
  struct  Objref_Traits< ::DefenseData::SitrepMessageDataWriter>
  {
    static ::DefenseData::SitrepMessageDataWriter_ptr duplicate (
        ::DefenseData::SitrepMessageDataWriter_ptr p);
    static void release (
        ::DefenseData::SitrepMessageDataWriter_ptr p);
    static ::DefenseData::SitrepMessageDataWriter_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::DefenseData::SitrepMessageDataWriter_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */

#if !defined (_DEFENSEDATA_SITREPMESSAGEDATAREADER__TRAITS_)
#define _DEFENSEDATA_SITREPMESSAGEDATAREADER__TRAITS_

  template<>
  struct  Objref_Traits< ::DefenseData::SitrepMessageDataReader>
  {
    static ::DefenseData::SitrepMessageDataReader_ptr duplicate (
        ::DefenseData::SitrepMessageDataReader_ptr p);
    static void release (
        ::DefenseData::SitrepMessageDataReader_ptr p);
    static ::DefenseData::SitrepMessageDataReader_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::DefenseData::SitrepMessageDataReader_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */
}
TAO_END_VERSIONED_NAMESPACE_DECL


// TAO_IDL - Generated from
// /home/martina-galli/OpenDDS/ACE_wrappers/TAO/TAO_IDL/be/be_codegen.cpp:1649

#if defined (__ACE_INLINE__)
#include "SitrepTypeSupportC.inl"
#endif /* defined INLINE */

#include /**/ "ace/post.h"

#endif /* ifndef */

